FROM apextoaster/node:16.19

# copy build output
COPY package.json yarn.lock /app/
COPY data/ /app/data/
COPY out/ /app/out/

WORKDIR /app

# install native modules
RUN yarn install --production

ENTRYPOINT [ "node", "/app/out/src/cli.js" ]
